os: linux             # ОС
sudo: required        # Необходимость прав sudo
language: "minimal"   # Языковой шаблон
script:
- cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install
- cmake --build _build
- cmake --build _build --target install

notifications:
    email: false
