os: linux             # ОС
sudo: required        # Необходимость прав sudo
language: "minimal"   # Языковой шаблон
services:
  - docker            # Необходимые сервисы
env:


  # Based on Alpine 3.10
  # GCC 8.3
  # CMake 3.14
  # gcovr
  # jscpd
  # valgrind
  # Hunter GTest v1.8.0 (cached)
  # Hunter Boost cached components: exception
  #                                 filesystem
  #                                 log
  #                                 regex
  #                                 system
 - DOCKER_IMAGE="toliak/bootstrap-cpp"             # Для использования снять комментарий

before_script:
  - docker pull $DOCKER_IMAGE                       # Предварительное скачивание образа

jobs:
  include:
  - name: "quality"
    script:
    - docker run -t -v $(pwd):/opt/builder/ --entrypoint ./scripts/duplication.sh toliak/bootstrap-cpp
  - name: "compile"
    script:
    - docker run -t -v $(pwd):/opt/builder/ --entrypoint ./scripts/compile.sh toliak/bootstrap-cpp

notifications:
    email: false
